# -*- mode: ruby -*-
# vi: set ft=ruby :
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

Vagrant.configure(2) do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 1
    vb.memory = "1500"
  end
  config.ssh.insert_key = false

  ################################################################################
  # Plugin: vagrant-vbguest
  # - vagrant plugin install vagrant-vbguest
  ################################################################################
  # set auto_update to false, if you do NOT want to check the correct
  # additions version when booting this machine
  config.vbguest.auto_update = true
  # do NOT download the iso file from a webserver
  config.vbguest.no_remote = true

  ################################################################################
  # Plugin: vagrant-gatling-rsync
  # - vagrant plugin install vagrant-gatling-rsync
  ################################################################################
  # Download rsync and add it to PATH: https://www.itefix.net/content/cwrsync-free-edition
  # Configure the window for gatling to coalesce writes.
  #if Vagrant.has_plugin?("vagrant-gatling-rsync")
  #  config.gatling.latency = 2.5
  #  config.gatling.time_format = "%H:%M:%S"
  #end
  # Automatically sync when machines with rsync folders come up.
  #config.gatling.rsync_on_startup = true

  config.vm.define "test" do |node|
    node.vm.box = "chaifeng/ubuntu-16.04-docker-18.03"
    node.vm.synced_folder "..", "/etc/ansible/roles/ansible-role-hashicorp-tools", :mount_options => ["ro"]
    #node.vm.synced_folder "..", "/etc/ansible/roles/role-under-test", type: "rsync", rsync__exclude: [".git/", ".vagrant/"]
    node.vm.provision "shell", run: "once" do |s|
      s.path = "vagrant-test.sh"
    end
  end
end